#!/bin/bash
#
# Author iMakhonin aka Makigo (Igor Makhonin)
# Email: <work.makhonin@gmail.com>
#
###

set -e

NAME=Yandekus
APPNAME=yandekus
VERSION=3.2
RELEASE=28.12.2016
EMAIL=work.makhonin@gmail.com
DATE=`date +%d/%m`
ADDRESS="yandex.ru"
XML="http://export.$ADDRESS/bar/reginfo.xml?region="
SOURCE="https://www.$ADDRESS"
WEATHER="pogoda"
MAPS="maps"
VAR_MAP="probki"
ERROR_EXT=" * Некорректные данные, исправьте ошибку."
ERROR_INT="Такой страницы не существует"
HELP="Используйте помощь: -h или --help"
COLLECT="Сбор данных:"
DEP_1=curl

txtund=$(tput sgr 0 1)          # Underline
txtbld=$(tput bold)             # Bold
bldgrn=${txtbld}$(tput setaf 2) # Bold Green
bldyel=${txtbld}$(tput setaf 3) # Bold Yellow
bldgyn=${txtbld}$(tput setaf 6) # Bold Gyn
red=$(tput setaf 1)             # Red
grn=$(tput setaf 2)             # Green
yel=$(tput setaf 3)             # Yello
blu=$(tput setaf 4)             # Blue
pur=$(tput setaf 5)             # Purple
gyn=$(tput setaf 6)             # Gyner
wht=$(tput setaf 7)             # White
rst=$(tput sgr0)                # Reset

  pbar0="$COLLECT   0% [${blu}.............................${rst}]"
 pbar10="$COLLECT  10% [${grn}==>${blu}..........................${rst}]"
 pbar20="$COLLECT  20% [${grn}=====>${blu}.......................${rst}]"
 pbar25="$COLLECT  25% [${grn}=======>${blu}.....................${rst}]"
 pbar30="$COLLECT  30% [${grn}=========>${blu}...................${rst}]"
 pbar35="$COLLECT  35% [${grn}===========>${blu}.................${rst}]"
 pbar40="$COLLECT  40% [${grn}============>${blu}................${rst}]"
 pbar50="$COLLECT  50% [${grn}===============>${blu}.............${rst}]"
 pbar60="$COLLECT  60% [${grn}=================>${blu}...........${rst}]"
 pbar65="$COLLECT  65% [${grn}===================>${blu}.........${rst}]"
 pbar70="$COLLECT  70% [${grn}====================>${blu}........${rst}]"
 pbar75="$COLLECT  75% [${grn}======================>${blu}......${rst}]"
 pbar80="$COLLECT  80% [${grn}========================>${blu}....${rst}]"
 pbar90="$COLLECT  90% [${grn}==========================>${blu}..${rst}]"
pbar100="$COLLECT ${grn}100%${rst} [${grn}=============================${rst}]"

### ─ ┬ ├ ≥ ┤ ▒ ° ± ┘ ┐ ┌ ≤ │ ┴ ┼ └ ###

### Функции
footer_a() {
  echo -e "Загружено за $SECONDS сек.\t   Источник ${SOURCE:8}"
}

footer_b() {
  echo -e "Загружено за $SECONDS сек.\t\t\t Источник ${SOURCE:8}"
}

check_dep() {
for deps in $DEP_1 $DEP_2
do
    if type $deps &>/dev/null
    then
        echo -e "   OK: $deps\t found"
    else
        dep_app=$deps
        echo -e "Error: $deps\t not found"
    fi
done
}

depends() {
  check_dep &>/dev/null
  if [ "$dep_app" != "" ]; then
    echo "*** Внимание! Для полноценной работы приложения \"$NAME\""
    echo "    Вам потребуется установить зависимость \"sudo apt-get install $dep_app\""
    exit 1
  fi
}

check_data() {
  a="curl -s $SOURCE/$WEATHER/$CODE"
  city_name=`exec $a | awk -F"title_level_1" '{print $2}' | cut -d ">" -f2 | cut -d "&" -f1 | sed 's/Погода в //g' | cut -d "<" -f1`
  city_code=`exec $a | awk -F"city=" '{print $2}' | cut -d "&" -f1`
}

check_xml() {
  a="curl -s $XML$CODE"
  t_city_rus=`exec $a | awk -F"<*>" '/title/ {print $2}' | cut -d "<" -f1`
  t_city_lat=`exec $a | awk -F"<*>" '/url slug/ {print $1}' | cut -d "\"" -f2`
}

ident_code() {
  if [ "$city_name" == "$ERROR_INT" ]; then
    echo "$ERROR_EXT"
    exit 1
  else
    echo "$city_code"
  fi
}

ident_city() {
  if [ "$city_name" == "$ERROR_INT" ]; then
    echo "$ERROR_EXT"
    exit 1
  else
    echo "Код отображает погоду в $city_name"
  fi
}

ident_code_full() {
  if [ "$city_name" == "$ERROR_INT" ]; then
    echo "$ERROR_EXT"
    exit 1
  else
    echo "Код <$city_code> по данным \"Яндекс\" отображает погоду в <$city_name>."
  fi
}

ident_city_full() {
  if [ "$city_name" == "$ERROR_INT" ]; then
    echo "$ERROR_EXT"
    exit 1
  else
    echo "Погоду в <$city_name> по данным \"Яндекс\" отображает код <$city_code>."
  fi
}

ident_weath() {
  if [ "$city_name" == "$ERROR_INT" ]; then
    echo "$ERROR_EXT"
    exit 1
  else
    weather
  fi
}

weather() {
  echo -ne "Пожалуйста подождите...\r"
  #c="curl -s $SOURCE/$WEATHER/$CODE"
  curl -s -o /tmp/$CODE.txt $SOURCE/$WEATHER/$CODE
  a="cat /tmp/$CODE.txt"
  echo -ne "$pbar0\r"
  ya_city=`exec $a | awk -F"title_level_1" '{print $2}' | cut -d ">" -f2 | cut -d "&" -f1 | sed 's/Погода в //g' | cut -d "<" -f1`
  echo -ne "$pbar10\r"
  ya_temp=`exec $a | awk -F"type_now" '/°C/ {print $3}' | cut -d ">" -f2 | cut -d "<" -f1`
  echo -ne "$pbar20\r"
  ya_rise=`exec $a | awk -F"info-label" '{print $2}' | cut -d ">" -f3 | cut -d "<" -f1`
  echo -ne "$pbar35\r"
  ya_sunset=`exec $a | awk -F"info-label" '{print $4}' | cut -d ">" -f3 | cut -d "<" -f1`
  echo -ne "$pbar50\r"
  ya_wind_s=`exec $a | awk -F"info-label" '{print $5}' | cut -d ">" -f4 | cut -d "<" -f1`
  echo -ne "$pbar65\r"
  ya_wind_d=`exec $a | awk -F"info-label" '{print $5}' | cut -d ">" -f6 | cut -d "<" -f1`
  echo -ne "$pbar70\r"
  ya_prs=`exec $a | awk -F"info-label" '{print $7}' | cut -d ">" -f3 | cut -d "<" -f1`
  echo -ne "$pbar80\r"
  ya_hum=`exec $a | awk -F"info-label" '{print $6}' | cut -d ">" -f3 | cut -d "<" -f1`
  echo -ne "$pbar100\r"
  echo -ne "\r"
  rm -f /tmp/$CODE.txt

    if [ "$ya_wind_s" == "Штиль  " ]; then
      tab="	"
    else
      tab=""
    fi

  echo "┌───────────────[ ${bldgyn}$NAME v$VERSION${rst} ]───────────────┐"
  echo "│         ${bldgrn}Погода в${rst} ${pur}...........${rst} ${bldgrn}$ya_city${rst}${tab_c}	│"
  echo "│      ${bldyel}Температура${rst} ${pur}...........${rst} ${txtbld}$ya_temp${rst}     	│"
  echo "│        ${bldyel}Влажность${rst} ${pur}...........${rst} ${txtbld}$ya_hum${rst}		│"
  echo "│         ${bldyel}Давление${rst} ${pur}...........${rst} ${txtbld}$ya_prs${rst} 	│"
  echo "│            ${bldyel}Ветер${rst} ${pur}...........${rst} ${txtbld}$ya_wind_s $ya_wind_d${tab}${rst}	│"
  echo "│           ${bldyel}Восход${rst} ${pur}...........${rst} ${txtbld}$ya_rise${rst}       	│"
  echo "│            ${bldyel}Закат${rst} ${pur}...........${rst} ${txtbld}$ya_sunset${rst}     	│"
  echo "└───────────────────────────────────────────────┘"
  footer_a
}

stock() {
  echo -ne "Пожалуйста подождите...\r"
  #a="curl -s $SOURCE"
  curl -s -o /tmp/$STOCK.txt $SOURCE
  a="cat /tmp/$STOCK.txt"
  echo -ne "$pbar0\r"
  ya_usd=`exec $a | awk -F"stocks__link" '/USD/ {print $2}' | cut -d "<" -f14 | cut -d ">" -f2`
  echo -ne "$pbar50\r"
  ya_eur=`exec $a | awk -F"stocks__link" '/EUR/ {print $3}' | cut -d "<" -f14 | cut -d ">" -f2`
  echo -ne "$pbar100\r"
  echo -ne "\r"
  rm -f /tmp/$STOCK.txt

  echo "┌───────────────[ ${bldgyn}$NAME v$VERSION${rst} ]───────────────┐"
  echo "│        ${bldyel}Доллар${rst} ${pur}...${rst} ${yel}на $DATE${rst} ${pur}...${rst} ${txtbld}$ya_usd${rst} р.       │"
  echo "│          ${bldyel}Евро${rst} ${pur}...${rst} ${yel}на $DATE${rst} ${pur}...${rst} ${txtbld}$ya_eur${rst} р.       │"
  echo "│                  ${bldgyn}Курсы валют${rst}                  │"
  echo "└───────────────────────────────────────────────┘"
  footer_a
}

traffic() {
  echo -ne "Пожалуйста подождите...\r"
  curl -s -o /tmp/$TRAFFIC.txt $XML$CODE
  a="cat /tmp/$TRAFFIC.txt"
  echo -ne "$pbar0\r"
  ya_traff=`exec $a | awk -F"<*>" '/level/ {print $2}' | cut -d "<" -f1`
  echo -ne "$pbar10\r"
  ya_temp=`exec $a | awk -F"<*>" '/temperature / {print $2}' | cut -d "<" -f1 | sort -u | tr -d '\r\n'`
  echo -ne "$pbar20\r"
  ya_city=`exec $a | awk -F"<*>" '/title/ {print $2}' | cut -d "<" -f1 | sort -u`
  echo -ne "$pbar30\r"
  ya_rise=`exec $a | awk -F"<*>" '/sun_rise/ {print $2}' | cut -d "<" -f1`
  echo -ne "$pbar40\r"
  ya_sunset=`exec $a | awk -F"<*>" '/sunset/ {print $2}' | cut -d "<" -f1`
  echo -ne "$pbar50\r"
  ya_country=`exec $a | awk -F"<*>" '/country/ {print $2}' | cut -d "<" -f1`
  echo -ne "$pbar60\r"
  ya_prs=`exec $a | awk -F"<*>" '/pressure/ {print $2}' | cut -d "<" -f1`
  echo -ne "$pbar65\r"
  ya_wind_s=`exec $a | awk -F"<*>" '/wind_speed/ {print $2}' | cut -d "<" -f1`
  echo -ne "$pbar70\r"
  ya_wind_d=`exec $a | awk -F"<*>" '/wind_direction/ {print $2}' | cut -d "<" -f1`
  echo -ne "$pbar75\r"
  ya_hum=`exec $a | awk -F"<*>" '/dampness/ {print $2}' | cut -d "<" -f1`
  echo -ne "$pbar80\r"
  ya_type=`exec $a | awk -F"<*>" '/weather_type/ {print $2}' | cut -d "<" -f1`
  echo -ne "$pbar90\r"
  ya_city_lat=`exec $a | awk -F"<*>" '/url slug/ {print $1}' | cut -d "\"" -f2`
  echo -ne "$pbar100\r"
  echo -ne "\r"
  rm -f /tmp/$TRAFFIC.txt
  if [ "$ya_traff" == "" ]; then
    ya_traff="-"
  fi

  dots=".............."

  printf "┌──────────────────────[ %s %s ]──────────────────────┐\n"          "${bldgyn}$NAME"              "v$VERSION${rst}"
  printf "│    %40s %s %s \t\t      │ \n"                                     "${bldyel}Страна${rst}"       "${pur}${dots}${rst}" "${txtbld}$ya_country${rst}"
  printf "│    %39s %s %s \t\t      │ \n"                                     "${bldyel}Город${rst}"        "${pur}${dots}${rst}" "${txtbld}$ya_city${rst}${tab_c}"
  printf "│    %40s %s %s \t      │ \n"                                       "${bldyel}Пробки${rst}"       "${pur}${dots}${rst}" "${txtbld}$ya_traff${rst} балл."
  printf "│    %45s %s %s \t\t      │ \n"                                     "${bldyel}Температура${rst}"  "${pur}${dots}${rst}" "${txtbld}$ya_temp${rst}°C"
  printf "│    %43s %s %s \t\t      │ \n"                                     "${bldyel}Влажность${rst}"    "${pur}${dots}${rst}" "${txtbld}$ya_hum${rst}%"
  printf "│    %42s %s %s \t      │ \n"                                       "${bldyel}Давление${rst}"     "${pur}${dots}${rst}" "${txtbld}$ya_prs мм рт.ст.${rst}"
  printf "│    %39s %s %s \t      │ \n"                                       "${bldyel}Ветер${rst}"        "${pur}${dots}${rst}" "${txtbld}$ya_wind_s м/с $ya_wind_d${tab}${rst}"
  printf "│    %40s %s %s \t\t      │ \n"                                     "${bldyel}Восход${rst}"       "${pur}${dots}${rst}" "${txtbld}$ya_rise${rst}"
  printf "│    %39s %s %s \t\t      │ \n"                                     "${bldyel}Закат${rst}"        "${pur}${dots}${rst}" "${txtbld}$ya_sunset${rst}"
  printf "│    %43s %s %s \t\t      │ \n"                                     "${bldyel}Параметры${rst}"    "${pur}${dots}${rst}" "${txtbld}$ya_type${rst}"
  printf "└─────────────────────────────────────────────────────────────┘\n"
  footer_b
}
###

### Команды
if [ "$1" == "-h"  ] || [ "$1" == "--help"  ] && [ -z "$2" ]; then
  echo "$NAME $VERSION, программа получения курса валют и погодных данных c Яндекс."
  echo "Использование: $APPNAME [КЛЮЧ]... [ГОРОД]..."
  echo
  echo "Команды на выбор:"
  echo "  -s,  --stock                 Отобразить курсы валют."
  echo "  -p,  --pogoda [name|code]   Отобразить полные метео данные используя код или имя города на англ."
  echo "  -w,  --weather [name|code]   Отобразить полные метео данные используя код или имя города на англ."
  echo "  -c,  --city [name city]      Отобразить код города (Используйте: имя города на англ.)."
  echo "  -c,  --code [code city]      Отобразить имя города (Используйте: код)."
  echo "  -i,  --info [name|code]      Отобразить полную информацию о название или коде города."
  echo "                               (Используйте: код или имя города на англ.)"
  echo "  -h,  --help                  Показать эту справку и выйти."
  echo "  -v,  --version               Показать информацию о версии и выйти."
  echo
  echo "Примеры:"
  echo "     $APPNAME -c 213      Вывод информации какому городу пренадлежит данный код."
  echo "     $APPNAME -p moscow   Вывод метео данных по городу Москва, также возможно ввести код (например: 213)."
  echo
  echo "Примечание:"
  echo "     Коды используются в соответствии с базой данных - Яндекс.Погода ($SOURCE/$WEATHER)." 
  echo
  echo "Об ошибках в \"$NAME\" сообщайте по адресу <$EMAIL>"
  exit 1

elif [ "$1" == "-v"  ] || [ "$1" == "--version"  ] && [ -z "$2" ]; then
  echo "Версия: $VERSION, дата релиза: $RELEASE"
  exit 1

elif [ "$1" == "-s"  ] || [ "$1" == "--stock"  ] && [ -z "$2" ]; then
  depends
  stock

elif [[ "$1" == "-p" || "$1" == "-w" || "$1" == "--pogoda" || "$1" == "--weather" && -n "$2" ]]; then
  depends
  CODE=$2
  check_data
  length=${#city_name}
    if [ "$length" -le "3" ]; then
      tab_c="       "
    elif [ "$length" -le "6" ]; then
      tab_c="     "
    elif [ "$length" -lt "9" ]; then
      tab_c="   "
    else
      tab_c=""
    fi
  ident_weath

elif [[ "$1" == "-c" && -n "$2" ]]; then
  depends
  CODE=$2
  check_data
  if [ "$2" == "$city_code" ]; then
    ident_city
  else
    ident_code
  fi

elif [[ "$1" == "--code" && -n "$2" ]]; then
  depends
  CODE=$2
  check_data
  ident_city

elif [[ "$1" == "--city" && -n "$2" ]]; then
  depends
  CODE=$2
  check_data
  ident_code

elif [[ "$1" == "-i" || "$1" == "--info" && -n "$2" ]]; then
  depends
  CODE=$2
  check_data
  if [ "$2" == "$city_code" ]; then
    ident_code_full
  else
    ident_city_full
  fi

elif [[ "$1" == "-t" || "$1" == "--traffic" && -n "$2" ]]; then
  depends
  CODE=$2
  check_data
  CODE=$city_code
  traffic

else
echo "$HELP"
fi
###

exit 0
